# Generated by Django 3.2.5 on 2021-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutme_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
